### PR TITLE
Update mods + Tweaker + added chipped/cobbled stone variants and recipes

### PR DESCRIPTION
**Pull request by Kevadroz**

### CODE REVIEW

**Review by FOREVEREALIZE — APPROVED** [review]
lgtm!

**Comment by FOREVEREALIZE** [comment]
You need to rebase onto master but otherwise, can merge.

**Comment by Kevadroz** [comment]
> You need to rebase onto master but otherwise, can merge.

How?

**Comment by FOREVEREALIZE** [comment]
> > You need to rebase onto master but otherwise, can merge.
> 
> How?

GitHub did it automagically, no need to worry

**Comment by Kevadroz** [comment]
> > > You need to rebase onto master but otherwise, can merge.
> > 
> > 
> > How?
> 
> GitHub did it automagically, no need to worry

No, I solved the conflict manually

**Comment by FOREVEREALIZE** [comment]
> > > > You need to rebase onto master but otherwise, can merge.
> > > 
> > > 
> > > How?
> > 
> > 
> > GitHub did it automagically, no need to worry
> 
> No, I solved the conflict manually

Oh, well, it merged nonetheless

**Pull request merged**
